/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.mercury.actors.msg;

import java.util.Optional;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class AvroMsg extends org.apache.avro.specific.SpecificRecordBase
		implements org.apache.avro.specific.SpecificRecord {
	private static final long serialVersionUID = -2335082975278536735L;
	public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
			"{\"type\":\"record\",\"name\":\"AvroMsg\",\"namespace\":\"io.mercury.actors.msg\",\"fields\":[{\"name\":\"type\",\"type\":\"int\"},{\"name\":\"content\",\"type\":\"bytes\"}]}");

	public static org.apache.avro.Schema getClassSchema() {
		return SCHEMA$;
	}

	private static SpecificData MODEL$ = new SpecificData();

	private static final BinaryMessageEncoder<AvroMsg> ENCODER = new BinaryMessageEncoder<AvroMsg>(MODEL$, SCHEMA$);

	private static final BinaryMessageDecoder<AvroMsg> DECODER = new BinaryMessageDecoder<AvroMsg>(MODEL$, SCHEMA$);

	/**
	 * Return the BinaryMessageEncoder instance used by this class.
	 * 
	 * @return the message encoder used by this class
	 */
	public static BinaryMessageEncoder<AvroMsg> getEncoder() {
		return ENCODER;
	}

	/**
	 * Return the BinaryMessageDecoder instance used by this class.
	 * 
	 * @return the message decoder used by this class
	 */
	public static BinaryMessageDecoder<AvroMsg> getDecoder() {
		return DECODER;
	}

	/**
	 * Create a new BinaryMessageDecoder instance for this class that uses the
	 * specified {@link SchemaStore}.
	 * 
	 * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
	 * @return a BinaryMessageDecoder instance for this class backed by the given
	 *         SchemaStore
	 */
	public static BinaryMessageDecoder<AvroMsg> createDecoder(SchemaStore resolver) {
		return new BinaryMessageDecoder<AvroMsg>(MODEL$, SCHEMA$, resolver);
	}

	/**
	 * Serializes this AvroMsg to a ByteBuffer.
	 * 
	 * @return a buffer holding the serialized data for this instance
	 * @throws java.io.IOException if this instance could not be serialized
	 */
	public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
		return ENCODER.encode(this);
	}

	/**
	 * Deserializes a AvroMsg from a ByteBuffer.
	 * 
	 * @param b a byte buffer holding serialized data for an instance of this class
	 * @return a AvroMsg instance decoded from the given buffer
	 * @throws java.io.IOException if the given bytes could not be deserialized into
	 *                             an instance of this class
	 */
	public static AvroMsg fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
		return DECODER.decode(b);
	}

	private int type;
	private java.nio.ByteBuffer content;

	/**
	 * Default constructor. Note that this does not initialize fields to their
	 * default values from the schema. If that is desired then one should use
	 * <code>newBuilder()</code>.
	 */
	public AvroMsg() {
	}

	/**
	 * All-args constructor.
	 * 
	 * @param type    The new value for type
	 * @param content The new value for content
	 */
	public AvroMsg(java.lang.Integer type, java.nio.ByteBuffer content) {
		this.type = type;
		this.content = content;
	}

	public org.apache.avro.specific.SpecificData getSpecificData() {
		return MODEL$;
	}

	public org.apache.avro.Schema getSchema() {
		return SCHEMA$;
	}

	// Used by DatumWriter. Applications should not call.
	public java.lang.Object get(int field$) {
		switch (field$) {
		case 0:
			return type;
		case 1:
			return content;
		default:
			throw new IndexOutOfBoundsException("Invalid index: " + field$);
		}
	}

	// Used by DatumReader. Applications should not call.
	public void put(int field$, java.lang.Object value$) {
		switch (field$) {
		case 0:
			type = (java.lang.Integer) value$;
			break;
		case 1:
			content = (java.nio.ByteBuffer) value$;
			break;
		default:
			throw new IndexOutOfBoundsException("Invalid index: " + field$);
		}
	}

	/**
	 * Gets the value of the 'type' field.
	 * 
	 * @return The value of the 'type' field.
	 */
	public int getType() {
		return type;
	}

	/**
	 * Gets the value of the 'type' field as an Optional&lt;java.lang.Integer&gt;.
	 * 
	 * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
	 */
	public Optional<java.lang.Integer> getOptionalType() {
		return Optional.<java.lang.Integer>ofNullable(type);
	}

	/**
	 * Sets the value of the 'type' field.
	 * 
	 * @param value the value to set.
	 */
	public void setType(int value) {
		this.type = value;
	}

	/**
	 * Gets the value of the 'content' field.
	 * 
	 * @return The value of the 'content' field.
	 */
	public java.nio.ByteBuffer getContent() {
		return content;
	}

	/**
	 * Gets the value of the 'content' field as an
	 * Optional&lt;java.nio.ByteBuffer&gt;.
	 * 
	 * @return The value wrapped in an Optional&lt;java.nio.ByteBuffer&gt;.
	 */
	public Optional<java.nio.ByteBuffer> getOptionalContent() {
		return Optional.<java.nio.ByteBuffer>ofNullable(content);
	}

	/**
	 * Sets the value of the 'content' field.
	 * 
	 * @param value the value to set.
	 */
	public void setContent(java.nio.ByteBuffer value) {
		this.content = value;
	}

	/**
	 * Creates a new AvroMsg RecordBuilder.
	 * 
	 * @return A new AvroMsg RecordBuilder
	 */
	public static io.mercury.actors.msg.AvroMsg.Builder newBuilder() {
		return new io.mercury.actors.msg.AvroMsg.Builder();
	}

	/**
	 * Creates a new AvroMsg RecordBuilder by copying an existing Builder.
	 * 
	 * @param other The existing builder to copy.
	 * @return A new AvroMsg RecordBuilder
	 */
	public static io.mercury.actors.msg.AvroMsg.Builder newBuilder(io.mercury.actors.msg.AvroMsg.Builder other) {
		if (other == null) {
			return new io.mercury.actors.msg.AvroMsg.Builder();
		} else {
			return new io.mercury.actors.msg.AvroMsg.Builder(other);
		}
	}

	/**
	 * Creates a new AvroMsg RecordBuilder by copying an existing AvroMsg instance.
	 * 
	 * @param other The existing instance to copy.
	 * @return A new AvroMsg RecordBuilder
	 */
	public static io.mercury.actors.msg.AvroMsg.Builder newBuilder(io.mercury.actors.msg.AvroMsg other) {
		if (other == null) {
			return new io.mercury.actors.msg.AvroMsg.Builder();
		} else {
			return new io.mercury.actors.msg.AvroMsg.Builder(other);
		}
	}

	/**
	 * RecordBuilder for AvroMsg instances.
	 */
	@org.apache.avro.specific.AvroGenerated
	public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroMsg>
			implements org.apache.avro.data.RecordBuilder<AvroMsg> {

		private int type;
		private java.nio.ByteBuffer content;

		/** Creates a new Builder */
		private Builder() {
			super(SCHEMA$);
		}

		/**
		 * Creates a Builder by copying an existing Builder.
		 * 
		 * @param other The existing Builder to copy.
		 */
		private Builder(io.mercury.actors.msg.AvroMsg.Builder other) {
			super(other);
			if (isValidValue(fields()[0], other.type)) {
				this.type = data().deepCopy(fields()[0].schema(), other.type);
				fieldSetFlags()[0] = other.fieldSetFlags()[0];
			}
			if (isValidValue(fields()[1], other.content)) {
				this.content = data().deepCopy(fields()[1].schema(), other.content);
				fieldSetFlags()[1] = other.fieldSetFlags()[1];
			}
		}

		/**
		 * Creates a Builder by copying an existing AvroMsg instance
		 * 
		 * @param other The existing instance to copy.
		 */
		private Builder(io.mercury.actors.msg.AvroMsg other) {
			super(SCHEMA$);
			if (isValidValue(fields()[0], other.type)) {
				this.type = data().deepCopy(fields()[0].schema(), other.type);
				fieldSetFlags()[0] = true;
			}
			if (isValidValue(fields()[1], other.content)) {
				this.content = data().deepCopy(fields()[1].schema(), other.content);
				fieldSetFlags()[1] = true;
			}
		}

		/**
		 * Gets the value of the 'type' field.
		 * 
		 * @return The value.
		 */
		public int getType() {
			return type;
		}

		/**
		 * Gets the value of the 'type' field as an Optional&lt;java.lang.Integer&gt;.
		 * 
		 * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
		 */
		public Optional<java.lang.Integer> getOptionalType() {
			return Optional.<java.lang.Integer>ofNullable(type);
		}

		/**
		 * Sets the value of the 'type' field.
		 * 
		 * @param value The value of 'type'.
		 * @return This builder.
		 */
		public io.mercury.actors.msg.AvroMsg.Builder setType(int value) {
			validate(fields()[0], value);
			this.type = value;
			fieldSetFlags()[0] = true;
			return this;
		}

		/**
		 * Checks whether the 'type' field has been set.
		 * 
		 * @return True if the 'type' field has been set, false otherwise.
		 */
		public boolean hasType() {
			return fieldSetFlags()[0];
		}

		/**
		 * Clears the value of the 'type' field.
		 * 
		 * @return This builder.
		 */
		public io.mercury.actors.msg.AvroMsg.Builder clearType() {
			fieldSetFlags()[0] = false;
			return this;
		}

		/**
		 * Gets the value of the 'content' field.
		 * 
		 * @return The value.
		 */
		public java.nio.ByteBuffer getContent() {
			return content;
		}

		/**
		 * Gets the value of the 'content' field as an
		 * Optional&lt;java.nio.ByteBuffer&gt;.
		 * 
		 * @return The value wrapped in an Optional&lt;java.nio.ByteBuffer&gt;.
		 */
		public Optional<java.nio.ByteBuffer> getOptionalContent() {
			return Optional.<java.nio.ByteBuffer>ofNullable(content);
		}

		/**
		 * Sets the value of the 'content' field.
		 * 
		 * @param value The value of 'content'.
		 * @return This builder.
		 */
		public io.mercury.actors.msg.AvroMsg.Builder setContent(java.nio.ByteBuffer value) {
			validate(fields()[1], value);
			this.content = value;
			fieldSetFlags()[1] = true;
			return this;
		}

		/**
		 * Checks whether the 'content' field has been set.
		 * 
		 * @return True if the 'content' field has been set, false otherwise.
		 */
		public boolean hasContent() {
			return fieldSetFlags()[1];
		}

		/**
		 * Clears the value of the 'content' field.
		 * 
		 * @return This builder.
		 */
		public io.mercury.actors.msg.AvroMsg.Builder clearContent() {
			content = null;
			fieldSetFlags()[1] = false;
			return this;
		}

		@Override
		public AvroMsg build() {
			try {
				AvroMsg record = new AvroMsg();
				record.type = fieldSetFlags()[0] ? this.type : (java.lang.Integer) defaultValue(fields()[0]);
				record.content = fieldSetFlags()[1] ? this.content : (java.nio.ByteBuffer) defaultValue(fields()[1]);
				return record;
			} catch (org.apache.avro.AvroMissingFieldException e) {
				throw e;
			} catch (java.lang.Exception e) {
				throw new org.apache.avro.AvroRuntimeException(e);
			}
		}
	}

	@SuppressWarnings("unchecked")
	private static final org.apache.avro.io.DatumWriter<AvroMsg> WRITER$ = (org.apache.avro.io.DatumWriter<AvroMsg>) MODEL$
			.createDatumWriter(SCHEMA$);

	@Override
	public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
		WRITER$.write(this, SpecificData.getEncoder(out));
	}

	@SuppressWarnings("unchecked")
	private static final org.apache.avro.io.DatumReader<AvroMsg> READER$ = (org.apache.avro.io.DatumReader<AvroMsg>) MODEL$
			.createDatumReader(SCHEMA$);

	@Override
	public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
		READER$.read(this, SpecificData.getDecoder(in));
	}

	@Override
	protected boolean hasCustomCoders() {
		return true;
	}

	@Override
	public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
		out.writeInt(this.type);

		out.writeBytes(this.content);

	}

	@Override
	public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
		org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
		if (fieldOrder == null) {
			this.type = in.readInt();

			this.content = in.readBytes(this.content);

		} else {
			for (int i = 0; i < 2; i++) {
				switch (fieldOrder[i].pos()) {
				case 0:
					this.type = in.readInt();
					break;

				case 1:
					this.content = in.readBytes(this.content);
					break;

				default:
					throw new java.io.IOException("Corrupt ResolvingDecoder.");
				}
			}
		}
	}
}
